package com.absurddevs.vespera.core.designsystem.theme

import androidx.compose.ui.graphics.Color

// Default theme

val vespera_theme_light_primary = Color(0xFF714D9F)
val vespera_theme_light_onPrimary = Color(0xFFFFFFFF)
val vespera_theme_light_primaryContainer = Color(0xFFEEDCFF)
val vespera_theme_light_onPrimaryContainer = Color(0xFF2A0054)
val vespera_theme_light_secondary = Color(0xFF5C53A7)
val vespera_theme_light_onSecondary = Color(0xFFFFFFFF)
val vespera_theme_light_secondaryContainer = Color(0xFFE4DFFF)
val vespera_theme_light_onSecondaryContainer = Color(0xFF170362)
val vespera_theme_light_tertiary = Color(0xFF4B57AB)
val vespera_theme_light_onTertiary = Color(0xFFFFFFFF)
val vespera_theme_light_tertiaryContainer = Color(0xFFDFE0FF)
val vespera_theme_light_onTertiaryContainer = Color(0xFF000D60)
val vespera_theme_light_error = Color(0xFFBA1A1A)
val vespera_theme_light_errorContainer = Color(0xFFFFDAD6)
val vespera_theme_light_onError = Color(0xFFFFFFFF)
val vespera_theme_light_onErrorContainer = Color(0xFF410002)
val vespera_theme_light_background = Color(0xFFFFFBFF)
val vespera_theme_light_onBackground = Color(0xFF1D1B1E)
val vespera_theme_light_surface = Color(0xFFFFFBFF)
val vespera_theme_light_onSurface = Color(0xFF1D1B1E)
val vespera_theme_light_surfaceVariant = Color(0xFFE8E0EB)
val vespera_theme_light_onSurfaceVariant = Color(0xFF4A454E)
val vespera_theme_light_outline = Color(0xFF7B757F)
val vespera_theme_light_inverseOnSurface = Color(0xFFF5EFF4)
val vespera_theme_light_inverseSurface = Color(0xFF322F33)
val vespera_theme_light_inversePrimary = Color(0xFFD9B9FF)
val vespera_theme_light_shadow = Color(0xFF000000)
val vespera_theme_light_surfaceTint = Color(0xFF714D9F)
val vespera_theme_light_outlineVariant = Color(0xFFCCC4CF)
val vespera_theme_light_scrim = Color(0xFF000000)

val vespera_theme_dark_primary = Color(0xFFD9B9FF)
val vespera_theme_dark_onPrimary = Color(0xFF401B6D)
val vespera_theme_dark_primaryContainer = Color(0xFF583485)
val vespera_theme_dark_onPrimaryContainer = Color(0xFFEEDCFF)
val vespera_theme_dark_secondary = Color(0xFFC7BFFF)
val vespera_theme_dark_onSecondary = Color(0xFF2D2276)
val vespera_theme_dark_secondaryContainer = Color(0xFF443A8E)
val vespera_theme_dark_onSecondaryContainer = Color(0xFFE4DFFF)
val vespera_theme_dark_tertiary = Color(0xFFBCC3FF)
val vespera_theme_dark_onTertiary = Color(0xFF19267A)
val vespera_theme_dark_tertiaryContainer = Color(0xFF323E91)
val vespera_theme_dark_onTertiaryContainer = Color(0xFFDFE0FF)
val vespera_theme_dark_error = Color(0xFFFFB4AB)
val vespera_theme_dark_errorContainer = Color(0xFF93000A)
val vespera_theme_dark_onError = Color(0xFF690005)
val vespera_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val vespera_theme_dark_background = Color(0xFF1D1B1E)
val vespera_theme_dark_onBackground = Color(0xFFE7E1E5)
val vespera_theme_dark_surface = Color(0xFF1D1B1E)
val vespera_theme_dark_onSurface = Color(0xFFE7E1E5)
val vespera_theme_dark_surfaceVariant = Color(0xFF4A454E)
val vespera_theme_dark_onSurfaceVariant = Color(0xFFCCC4CF)
val vespera_theme_dark_outline = Color(0xFF958E99)
val vespera_theme_dark_inverseOnSurface = Color(0xFF1D1B1E)
val vespera_theme_dark_inverseSurface = Color(0xFFE7E1E5)
val vespera_theme_dark_inversePrimary = Color(0xFF714D9F)
val vespera_theme_dark_shadow = Color(0xFF000000)
val vespera_theme_dark_surfaceTint = Color(0xFFD9B9FF)
val vespera_theme_dark_outlineVariant = Color(0xFF4A454E)
val vespera_theme_dark_scrim = Color(0xFF000000)


val vespera_seed = Color(0xFFDBCEE5)

// Android theme
val android_theme_light_primary = Color(0xFF006D3B)
val android_theme_light_onPrimary = Color(0xFFFFFFFF)
val android_theme_light_primaryContainer = Color(0xFF66FEA2)
val android_theme_light_onPrimaryContainer = Color(0xFF00210E)
val android_theme_light_secondary = Color(0xFF4F6353)
val android_theme_light_onSecondary = Color(0xFFFFFFFF)
val android_theme_light_secondaryContainer = Color(0xFFD2E8D4)
val android_theme_light_onSecondaryContainer = Color(0xFF0D1F13)
val android_theme_light_tertiary = Color(0xFF3A646F)
val android_theme_light_onTertiary = Color(0xFFFFFFFF)
val android_theme_light_tertiaryContainer = Color(0xFFBEEAF6)
val android_theme_light_onTertiaryContainer = Color(0xFF001F26)
val android_theme_light_error = Color(0xFFBA1A1A)
val android_theme_light_errorContainer = Color(0xFFFFDAD6)
val android_theme_light_onError = Color(0xFFFFFFFF)
val android_theme_light_onErrorContainer = Color(0xFF410002)
val android_theme_light_background = Color(0xFFFBFDF8)
val android_theme_light_onBackground = Color(0xFF191C19)
val android_theme_light_surface = Color(0xFFFBFDF8)
val android_theme_light_onSurface = Color(0xFF191C19)
val android_theme_light_surfaceVariant = Color(0xFFDDE5DB)
val android_theme_light_onSurfaceVariant = Color(0xFF414942)
val android_theme_light_outline = Color(0xFF717971)
val android_theme_light_inverseOnSurface = Color(0xFFF0F1EC)
val android_theme_light_inverseSurface = Color(0xFF2E312E)
val android_theme_light_inversePrimary = Color(0xFF43E188)
val android_theme_light_shadow = Color(0xFF000000)
val android_theme_light_surfaceTint = Color(0xFF006D3B)
val android_theme_light_outlineVariant = Color(0xFFC1C9BF)
val android_theme_light_scrim = Color(0xFF000000)

val android_theme_dark_primary = Color(0xFF43E188)
val android_theme_dark_onPrimary = Color(0xFF00391C)
val android_theme_dark_primaryContainer = Color(0xFF00522B)
val android_theme_dark_onPrimaryContainer = Color(0xFF66FEA2)
val android_theme_dark_secondary = Color(0xFFB6CCB8)
val android_theme_dark_onSecondary = Color(0xFF223527)
val android_theme_dark_secondaryContainer = Color(0xFF384B3C)
val android_theme_dark_onSecondaryContainer = Color(0xFFD2E8D4)
val android_theme_dark_tertiary = Color(0xFFA2CEDA)
val android_theme_dark_onTertiary = Color(0xFF023640)
val android_theme_dark_tertiaryContainer = Color(0xFF214C57)
val android_theme_dark_onTertiaryContainer = Color(0xFFBEEAF6)
val android_theme_dark_error = Color(0xFFFFB4AB)
val android_theme_dark_errorContainer = Color(0xFF93000A)
val android_theme_dark_onError = Color(0xFF690005)
val android_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val android_theme_dark_background = Color(0xFF191C19)
val android_theme_dark_onBackground = Color(0xFFE1E3DE)
val android_theme_dark_surface = Color(0xFF191C19)
val android_theme_dark_onSurface = Color(0xFFE1E3DE)
val android_theme_dark_surfaceVariant = Color(0xFF414942)
val android_theme_dark_onSurfaceVariant = Color(0xFFC1C9BF)
val android_theme_dark_outline = Color(0xFF8B938A)
val android_theme_dark_inverseOnSurface = Color(0xFF191C19)
val android_theme_dark_inverseSurface = Color(0xFFE1E3DE)
val android_theme_dark_inversePrimary = Color(0xFF006D3B)
val android_theme_dark_shadow = Color(0xFF000000)
val android_theme_dark_surfaceTint = Color(0xFF43E188)
val android_theme_dark_outlineVariant = Color(0xFF414942)
val android_theme_dark_scrim = Color(0xFF000000)


val android_seed = Color(0xFF3DDC84)