package com.absurddevs.vespera.ui.theme

import androidx.compose.ui.graphics.Color

val vespera_light_primary = Color(0xFF6750A4)
val vespera_light_onPrimary = Color(0xFFFFFFFF)
val vespera_light_primaryContainer = Color(0xFFE9DDFF)
val vespera_light_onPrimaryContainer = Color(0xFF22005D)
val vespera_light_secondary = Color(0xFF625B71)
val vespera_light_onSecondary = Color(0xFFFFFFFF)
val vespera_light_secondaryContainer = Color(0xFFE8DEF8)
val vespera_light_onSecondaryContainer = Color(0xFF1E192B)
val vespera_light_tertiary = Color(0xFF6750A4)
val vespera_light_onTertiary = Color(0xFFFFFFFF)
val vespera_light_tertiaryContainer = Color(0xFFE9DDFF)
val vespera_light_onTertiaryContainer = Color(0xFF22005D)
val vespera_light_error = Color(0xFFBA1A1A)
val vespera_light_errorContainer = Color(0xFFFFDAD6)
val vespera_light_onError = Color(0xFFFFFFFF)
val vespera_light_onErrorContainer = Color(0xFF410002)
val vespera_light_background = Color(0xFFFFFBFF)
val vespera_light_onBackground = Color(0xFF1C1B1E)
val vespera_light_surface = Color(0xFFFFFBFF)
val vespera_light_onSurface = Color(0xFF1C1B1E)
val vespera_light_surfaceVariant = Color(0xFFE7E0EB)
val vespera_light_onSurfaceVariant = Color(0xFF49454E)
val vespera_light_outline = Color(0xFF7A757F)
val vespera_light_inverseOnSurface = Color(0xFFF4EFF4)
val vespera_light_inverseSurface = Color(0xFF313033)
val vespera_light_inversePrimary = Color(0xFFCFBCFF)
val vespera_light_shadow = Color(0xFF000000)
val vespera_light_surfaceTint = Color(0xFF6750A4)
val vespera_light_outlineVariant = Color(0xFFCAC4CF)
val vespera_light_scrim = Color(0xFF000000)

val vespera_dark_primary = Color(0xFFCFBCFF)
val vespera_dark_onPrimary = Color(0xFF381E72)
val vespera_dark_primaryContainer = Color(0xFF4F378A)
val vespera_dark_onPrimaryContainer = Color(0xFFE9DDFF)
val vespera_dark_secondary = Color(0xFFCBC2DB)
val vespera_dark_onSecondary = Color(0xFF332D41)
val vespera_dark_secondaryContainer = Color(0xFF4A4458)
val vespera_dark_onSecondaryContainer = Color(0xFFE8DEF8)
val vespera_dark_tertiary = Color(0xFFCFBDFF)
val vespera_dark_onTertiary = Color(0xFF371E73)
val vespera_dark_tertiaryContainer = Color(0xFF4E378A)
val vespera_dark_onTertiaryContainer = Color(0xFFE9DDFF)
val vespera_dark_error = Color(0xFFFFB4AB)
val vespera_dark_errorContainer = Color(0xFF93000A)
val vespera_dark_onError = Color(0xFF690005)
val vespera_dark_onErrorContainer = Color(0xFFFFDAD6)
val vespera_dark_background = Color(0xFF1C1B1E)
val vespera_dark_onBackground = Color(0xFFE6E1E6)
val vespera_dark_surface = Color(0xFF1C1B1E)
val vespera_dark_onSurface = Color(0xFFE6E1E6)
val vespera_dark_surfaceVariant = Color(0xFF49454E)
val vespera_dark_onSurfaceVariant = Color(0xFFCAC4CF)
val vespera_dark_outline = Color(0xFF948F99)
val vespera_dark_inverseOnSurface = Color(0xFF1C1B1E)
val vespera_dark_inverseSurface = Color(0xFFE6E1E6)
val vespera_dark_inversePrimary = Color(0xFF6750A4)
val vespera_dark_shadow = Color(0xFF000000)
val vespera_dark_surfaceTint = Color(0xFFCFBCFF)
val vespera_dark_outlineVariant = Color(0xFF49454E)
val vespera_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF6750A4)